### PR TITLE
chore: upgrade actions pinning

### PR DESCRIPTION
**Pull request by fubuloubu**
Check this one manually before updating `v1` tag

### CODE REVIEW

**Comment by fubuloubu** [comment]
@sabotagebeats to check this one, I think make or update a repo with `uses: ApeWorX/github-action@chore/upgrade-actions` as a step, such as https://github.com/fubuloubu/WETH8 or something sufficiently complex

**Comment by sabotagebeats** [comment]
Am I doing this right @fubuloubu https://github.com/ApeWorX/ape/pull/1234

**Comment by fubuloubu** [comment]
> Am I doing this right @fubuloubu [ApeWorX/ape#1234](https://github.com/ApeWorX/ape/pull/1234)

Oh, you should be doing this on an ape project repo, like the one I linked or something you have

**Comment by sabotagebeats** [comment]
> > Am I doing this right @fubuloubu [ApeWorX/ape#1234](https://github.com/ApeWorX/ape/pull/1234)
> 
> Oh, you should be doing this on an ape project repo, like the one I linked or something you have

OK great I'll give that a shot. Thanks!

**Comment by fubuloubu** [comment]
Checked it working here: https://github.com/fubuloubu/WETH8/pull/2#issuecomment-1400795615

Might want to test with a different project though, appears like that project's test aren't currently functioning

**Pull request merged**
